### ISSUE TITLE
High Priority - Targeting Grid

### ISSUE THREAD

**Issue by RyanRules23** [sirhunkzalot/Harpaesis#199]
this bug occurs when you press an attack with a unit then hit enter the targeting grid does not appear, this is repeatable every tim
![Capture](https://user-images.githubusercontent.com/73117357/164268389-6d6510f9-d8c6-4bb7-b888-f862cf2a8135.PNG)
e

**Comment by sirhunkzalot** [comment]
Problem Found: Ending turn needs to disable active Targeting Templates

Not Yet Implemented

**Comment by sirhunkzalot** [comment]
Resolved
