### ISSUE TITLE
High Priority - Negative AP

### ISSUE THREAD

**Issue by RyanRules23** [sirhunkzalot/Harpaesis#200]
this bug is also repeatable with Joachim's teriary skill, there is an issue where if you move to have 1-2 AP remaining you can still use the action and you end up getting a negative A
![-AP bug](https://user-images.githubusercontent.com/73117357/164269537-701b5743-745d-420e-9165-f6d7dd64be30.PNG)
P

**Comment by RyanRules23** [comment]
this also appears to happen on joachin's secondary skill as well

**Comment by sirhunkzalot** [comment]
Resolved
